In [96]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

# Series : 일련의 객체를 담을 수 있는 1차원 배열 같은 자료 구조
obj = pd.Series([4, 7, -5, 3])
print(obj)
print()
print(obj.values)
print()
print(obj.index) # range(4)와 같다
print()
obj2 = pd.Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])
print(obj2)
print()
print(obj2['a'])
print()
print(obj2[['d', 'a']]) # 색인으로 라벨을 사용할 수 있다
print()
print(obj2[obj2>0])
print()
print(np.exp(obj2))
print()
print('b' in obj2)
print()
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64

[ 4  7 -5  3]

RangeIndex(start=0, stop=4, step=1)

d    4
b    7
a   -5
c    3
dtype: int64

-5

d    4
a   -5
dtype: int64

d    4
b    7
c    3
dtype: int64

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

True

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64


In [28]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}
obj3 = pd.Series(sdata)
print(obj3)
print()
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index = states)
print(obj4)
print()
print(pd.isnull(obj4))
print()
print(pd.notnull(obj4))
print()
print(obj4.isnull())
print()
print(obj3 + obj4)
print()
obj4.name = 'population'
obj4.index.name = 'state'
print(obj4)


Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64


In [32]:
# DataFrame : 표 같은 스프레드 시트 형식의 자료구조

data = {'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year' : [2000, 2001, 2002, 2001, 2002, 2003],
       'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [33]:
frame.head() # 큰 DataFrame을 다룰 때는 head 메서드를 이용해서 처음 5개의 row만 출력할 수도 있다.

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [34]:
pd.DataFrame(data, columns=['year', 'state', 'pop']) 
# 원하는 순서대로 columns를 지정하면 원하는 순서를 가진 DataFrame 객체가 생성된다

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [35]:
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'],
                     index = ['one', 'two', 'three', 'four', 
                              'five', 'six'])
frame2
# Series와 마찬가지로 사전에 없는 값을 넘기면 결측치로 저장된다

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [36]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [37]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [38]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [39]:
frame2.loc['three'] # columns와 달리 rows는 loc속성을 이용해서 이름을 통해 접근할 수 있다.

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [40]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [42]:
frame2['debt'] = np.arange(6.)
frame2
# columns는 대입이 가능하다. (스칼라값, 배열 등등..)

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [45]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])
frame2['debt'] = val
frame2
# Series를 대입하면 DataFrame의 색인에 따라 값이 대입되며 존재하지 않는 색인에는 결측치가 대입된다

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [49]:
frame2['eastern'] = frame2.state == 'Ohio' # 새로운 columns 대입
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [50]:
del frame2['eastern'] # del 예약어로 columns 삭제 가능
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [52]:
pop = {'Nevada' : {2001 : 2.4, 2002 : 2.9},
      'Ohio' : {2000 : 1.5, 2001 : 1.7, 2002 : 3.6}}
# 사전의 키는 columns가 되고 안에 있는 키는 rows가 된다.
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [53]:
frame3.T 
# Numpy 배열과 유사한 문법으로 데이터를 전치(columns와 rows를 뒤짐음)할 수 있다.

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [54]:
pd.DataFrame(pop, index=[2001, 2002, 2003]) # 색인 직접 지정 가능

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [55]:
pdata = {'Ohio' : frame3['Ohio'][:-1],
        'Nevada' : frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [56]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [57]:
frame3.values
# Series와 유사하게 values속성은 DataFrame에 저장된 데이터를 2차원 배열로 반환한다.

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [58]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [61]:
obj = pd.Series(range(3), index = ['a', 'b', 'c'])
index = obj.index
print(index)
print()
print(index[1:])

Index(['a', 'b', 'c'], dtype='object')

Index(['b', 'c'], dtype='object')


In [65]:
labels = pd.Index(np.arange(3))
print(labels)
print()
obj2 = pd.Series([1.5, -2.5, 0],index=labels)
print(obj2)
print()
print(obj2.index is labels)

Int64Index([0, 1, 2], dtype='int64')

0    1.5
1   -2.5
2    0.0
dtype: float64

True


In [68]:
print(frame3)
print()
print(frame3.columns)
print()
print('Ohio' in frame3.columns)

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

Index(['Nevada', 'Ohio'], dtype='object', name='state')

True


In [69]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [73]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])
print(obj)
print()
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
print(obj2)
# Series 객체에 대해 reindex를 호출하면 데이터를 새로운 색인에 맞게 재배열하고 존재 하지 않는 색인 값이 있다면 NAN을 추가한다

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64


In [77]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])
print(obj3)
print()
print(obj3.reindex(range(6), method = 'ffill'))
# ffill 메서드를 통해 누락된 값을 직전의 값으로 채워 넣을 수 있다

0      blue
2    purple
4    yellow
dtype: object

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object


In [88]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                     index = ['a', 'c', 'd'],
                     columns = ['Ohio', 'Texas', 'California'])
print(frame)
print()
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
print(frame2)
print()
states = ['Texas', 'Utah', 'California']
print(frame.reindex(columns=states))

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8


In [91]:
obj = pd.Series(np.arange(5.), index=('a', 'b', 'c', 'd', 'e'))
print(obj)
print()
new_obj = obj.drop('c')
print(new_obj)
print()
print(obj.drop(['c', 'd'])) # drop 메서드로 선택한 값들이 삭제된 새로운 객체 생성 가능

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

a    0.0
b    1.0
e    4.0
dtype: float64


In [92]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [94]:
data.drop(['Colorado', 'Ohio'])
# drop 함수에 인자로 row 이름을 넘기면 해당 row(axis=0)의 값을 모두 삭제한다

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [95]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [96]:
data.drop(['two', 'four'], axis = 'columns')
# columns의 값을 삭제할 때는 axis=1 또는 axis='columns'를 넘겨주면 된다

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [106]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
print(obj)
print()
print(obj['b'])
print()
print(obj[1])
print()
print(obj[2:4])
print()
print(obj[obj<2])
print()
print(obj['b':'c']) # 라벨 이름으로 슬라이싱하면 시작점과 끝점을 포함한다. (일반 파이썬 슬라이싱은 끝점-1)
print()
obj['b':'c'] = 5
print(obj)

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

1.0

1.0

c    2.0
d    3.0
dtype: float64

a    0.0
b    1.0
dtype: float64

b    1.0
c    2.0
dtype: float64

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64


In [107]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [108]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [109]:
data[['three', 'two']]

three  two
Ohio          2    1
Colorado      6    5
Utah         10    9
New York     14   13

In [111]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [112]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [113]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [115]:
data[data<5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [121]:
# loc과 iloc로 선택하기
# 이 방법을 이용하면 Numpy와 비슷한 방식에 추가적으로 축의 라벨을 사용하여 DataFrame의 row와 column을 선택할 수 있다.
# 축 이름을 선택할 때는 loc, 정수 색인으로 선택할 때는 iloc을 사용한다.
print(data.loc['Colorado', ['two', 'three']])
print()
print(data.iloc[2, [3,0,1]])
print()
print(data.iloc[2])
print()
print(data.iloc[[1,2], [3,0,1]])
print()
print(data.loc[:'Utah', 'two'])
print()
print(data.iloc[:,:3][data.three>5])

two      5
three    6
Name: Colorado, dtype: int64

four    11
one      8
two      9
Name: Utah, dtype: int64

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

          four  one  two
Colorado     7    0    5
Utah        11    8    9

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14


In [129]:
ser = pd.Series(np.arange(3.))
print(ser)
print()
ser2 = pd.Series(np.arange(3.), index = ['a', 'b', 'c'])
print(ser2[-1])
print()
print(ser[:1])
print()
print(ser.loc[:1])
print()
print(ser.iloc[:1])

0    0.0
1    1.0
2    2.0
dtype: float64

2.0

0    0.0
dtype: float64

0    0.0
1    1.0
dtype: float64

0    0.0
dtype: float64


In [133]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
print(s1)
print()
print(s2)
print()
print(s1 + s2)
# Series의 경우 서로 겹치는 색인이 없을 때는 데이터가 NA값이 된다.

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64


In [4]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns = list('bcd'),
                  index = ['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'),
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [135]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [8]:
df1 + df2 
# 두 DataFrame을 더하면 각 DataFrame에 있는 색인과 column이 하나로 합쳐진다.

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [9]:
df1 = pd.DataFrame({'A': [1,2]})
df2 = pd.DataFrame({'B': [3,4]})
df1

A
0  1
1  2

In [10]:
df2

B
0  3
1  4

In [12]:
df1-df2
# df1 과 df2이 공통 column 라벨 이나 row 라벨이 없으므로 결과값이 나타나지 않는다. 

A   B
0 NaN NaN
1 NaN NaN

In [17]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                  columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                  columns=list('abcde'))
df2.loc[1,'b'] = np.nan

df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [18]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [19]:
df1 + df2
# 겹치지 않는 부분은 NA가 된다

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [20]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [21]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [22]:
df1.reindex(columns=df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [24]:
arr = np.arange(12.).reshape((3,4))
print(arr)
print()
print(arr[0])
print()
print(arr-arr[0]) # 각 로우에 한번 씩 수행한다 : BroadCasting

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[0. 1. 2. 3.]

[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]


In [26]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                        columns = list('bde'),
                        index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [27]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [28]:
frame - series
# 모든 row에 각각 수행됌 : BroadCasting

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [33]:
series2 = pd.Series(np.arange(3), index = ['b', 'e', 'f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [37]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [38]:
frame.sub(series3, axis = 'index')
# 인자로 넘기는 axis 값은 연산을 적용할 축 번호이다.
# axis = 'index'나 axis=0 은 DataFrame의 row를 따라 연산을 수행하라는 의미다.

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [40]:
frame - series3

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [44]:
frame = pd.DataFrame(np.random.randn(4,3), columns = list('bde'),
                    index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -1.684212  3.238997  1.064675
Ohio    0.297539 -0.010197 -0.876751
Texas  -0.450578  0.580277 -2.407591
Oregon  1.051828 -0.364355  0.818281

In [45]:
np.abs(frame)

b         d         e
Utah    1.684212  3.238997  1.064675
Ohio    0.297539  0.010197  0.876751
Texas   0.450578  0.580277  2.407591
Oregon  1.051828  0.364355  0.818281

In [46]:
f= lambda x : x.max()- x.min()
frame.apply(f)

b    2.736040
d    3.603352
e    3.472265
dtype: float64

In [47]:
frame.apply(f, axis = 'columns')
# axis = columns 인자를 넘기면 각 row에 대해 한 번씩 수행한다

Utah      4.923209
Ohio      1.174290
Texas     2.987868
Oregon    1.416183
dtype: float64

In [48]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])
frame.apply(f)

b         d         e
min -1.684212 -0.364355 -2.407591
max  1.051828  3.238997  1.064675

In [51]:
format = lambda x : '%.2f' % x
frame.applymap(format)
# 메서드 이름이 applymap 인 이유? : Series는 각 원소에 적용할 함수를 지정하기 위한 map 메서드를 가지고 있기 때문

b      d      e
Utah    -1.68   3.24   1.06
Ohio     0.30  -0.01  -0.88
Texas   -0.45   0.58  -2.41
Oregon   1.05  -0.36   0.82

In [52]:
frame['e'].map(format)

Utah       1.06
Ohio      -0.88
Texas     -2.41
Oregon     0.82
Name: e, dtype: object

In [53]:
obj = pd.Series(range(4), index = ['d', 'a', 'b', 'c'])
obj.sort_index() # sort_index 메서드로 row나 column의 색인을 정렬해서 새로운 객체를 반환할 수 있다.

a    1
b    2
c    3
d    0
dtype: int64

In [54]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index = ['three', 'one'],
                    columns = ['d', 'a', 'b', 'c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [55]:
frame.sort_index(axis=1) # axis=1 : columns 기준 정렬

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [56]:
frame.sort_index(axis=1, ascending=False) # 기본적으로 오름차순 정렬이지만 내림차순으로 정렬할 수도 있다

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [58]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()
# 비어 있는 값은 기본적으로 가장 마지막에 위치한다.

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [61]:
frame = pd.DataFrame({'b' : [4, 7, -3, 2], 'a' : [0, 1, 0, 1 ]})
frame2 = frame.sort_index(axis=1)
frame2

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [64]:
print(frame2.sort_values(by='b'))
print()
# 하나 이상의 column에 있는 값으로 정렬을 하는 경우 sort_values 함수의 by 옵션에 하나 이상의 column 이름을 넘기면 된다
print(frame2.sort_values(by=['a', 'b']))

   a  b
2  0 -3
3  1  2
0  0  4
1  1  7

   a  b
2  0 -3
0  0  4
3  1  2
1  1  7


In [68]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
print(obj.rank()) # 작은 것부터 rank 메김(오름차순)
print()
print(obj.rank(method='first'))
print()
print(obj.rank(ascending=False, method='max')) # 내림차순 

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64


In [72]:
frame = pd.DataFrame({'b' : [4.3, 7, -3, 2], 'a' : [0, 1, 0, 1], 'c' : [-2, 5, 8, -2.5]})
frame.sort_index(axis=1)

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [71]:
frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [76]:
obj = pd.Series(range(5), index = ['a', 'a', 'b', 'b', 'c'])
print(obj)
print()
print(obj.index.is_unique)
print()
print(obj['a'])

a    0
a    1
b    2
b    3
c    4
dtype: int64

False

a    0
a    1
dtype: int64


In [77]:
df = pd.DataFrame(np.random.randn(4, 3), index = ['a', 'a', 'b', 'b'])
df

0         1         2
a  1.079523 -0.411169 -0.125989
a -0.100552  1.613439  1.631189
b  0.216801 -0.263408  0.446258
b -0.189406 -1.244974 -1.429920

In [78]:
df.loc['b']

0         1         2
b  0.216801 -0.263408  0.446258
b -0.189406 -1.244974 -1.429920

In [79]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75, -1.3]],
                 index = ['a', 'b', 'c', 'd'],
                 columns = ['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [80]:
df.sum() # sum 메서드로 각 column의 합을 담은 Series를 반환한다

one    9.25
two   -5.80
dtype: float64

In [83]:
print(df.sum(axis=1))
print()
print(df.sum(axis='columns'))

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64


In [84]:
df.mean(axis=1, skipna=False)
# NA 값은 제외하고 계산된다

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [85]:
df.idxmax()
# idxmin(), idxmax() 는 최솟값 혹은 최댓값을 가지고 있는 색인값과 같은 간접 통계를 반환한다

one    b
two    d
dtype: object

In [86]:
df.cumsum()
# accumulation

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [87]:
df.describe()
# 한 번에 여러개의 통계 결과를 반환한다

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [89]:
obj = pd.Series(['a', 'a', 'b', 'c']*4)
obj.describe()
# 수치 데이터가 아닐 경우 decribe()는 다른 요약 통계 결과를 반환한다

count     16
unique     3
top        a
freq       8
dtype: object

In [99]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
uniques = obj.unique() # unique 메서드는 중복되는 값을 제거하고 유일값만 담고 있는 Series를 반환한다
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [100]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [101]:
pd.value_counts(obj.values, sort = False)

c    3
b    2
a    3
d    1
dtype: int64

In [102]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [104]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [105]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [106]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match) 
# Index.get_indexer 메서드는 여러 값이 들어 있는 배열에서 유일한 값의 색인 배열을 구할 수 있다.

array([0, 2, 1, 1, 0, 2])

In [107]:
data = pd.DataFrame({'Qu1' : [1, 3, 4, 3, 4],
                    'Qu2' : [2, 3, 1, 2, 3],
                    'Qu3' : [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [109]:
result = data.apply(pd.value_counts).fillna(0)
result
# row 라벨(1,2,3,4,5)는 전체 column의 유일한 값들을 담고 있다. 각 값은 각 column에서 해당 값이 몇번 출현했는지 나타낸다.

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0